apiVersion: v1
kind: Secret
metadata:
  name: nxd-secret
type: Opaque
stringData:
    NXD_INTERVAL: "5"
    NXD_TIMEZONE: "UTC"
    NXD_TOKEN: "discord-bot-token-here"
    NXD_DB: "mongodb+srv://root:pass@host:port/nyaaXdiscord?retryWrites=true&w=majority"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxd-deployment
  labels:
    app: nxd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxd
  template:
    metadata:
      generateName: nxd-pod-
      labels:
        app: nxd
    spec:
      containers:
        - name: nyaa-x-discord
          image: rl404/nyaa-x-discord:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nxd-secret