apiVersion: v1
kind: Secret
metadata:
  name: nxd-secret
type: Opaque
stringData:
    NXD_INTERVAL: "10"
    NXD_PREFIX: "!"
    NXD_TOKEN: "discord-bot-token-here"
    NXD_DB_URI: "mongodb://localhost:27017/nyaaXdiscord"
    NXD_DB_USER: "root"
    NXD_DB_PASSWORD: "pass"
    NXD_ES_ADDRESS: "http://localhost:9200"
    NXD_ES_USER: ""
    NXD_ES_PASSWORD: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxd-deployment
  labels:
    app: nxd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxd
  template:
    metadata:
      generateName: nxd-pod-
      labels:
        app: nxd
    spec:
      containers:
        - name: nyaa-x-discord
          image: rl404/nyaa-x-discord:latest
          imagePullPolicy: IfNotPresent
          command: ["/nxd"]
          args: ["bot"]
          envFrom:
            - secretRef:
                name: nxd-secret
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nxd-cron-deployment
  labels:
    app: mal-cron
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: nxd-cron
              image: rl404/nyaa-x-discord:latest
              imagePullPolicy: IfNotPresent
              command: ["/nxd"]
              args: ["check"]
              envFrom:
                - secretRef:
                    name: nxd-secret