name: import terraform

on: workflow_dispatch

jobs:
  import_terraform:
    name: Import Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/terraform
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Auth gcloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id           = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region               = "${{ secrets.GCP_REGION }}"
          gke_cluster_name         = "${{ secrets.GKE_CLUSTER_NAME }}"
          gke_location             = "${{ secrets.GKE_LOCATION }}"
          gke_pool_name            = "${{ secrets.GKE_POOL_NAME }}"
          gke_node_preemptible     = "${{ secrets.GKE_NODE_PREEMPTIBLE }}"
          gke_node_machine_type    = "${{ secrets.GKE_NODE_MACHINE_TYPE }}"
          gke_node_disk_size_gb    = "${{ secrets.GKE_NODE_DISK_SIZE_GB }}"
          gcr_image_name           = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/nyaa-x-discord:${{ needs.publish_image.outputs.img_tag }}"
          gke_deployment_name      = "${{ secrets.GKE_DEPLOYMENT_NAME }}"
          gke_cron_name            = "${{ secrets.GKE_CRON_NAME }}"
          gke_cron_schedule        = "${{ secrets.GKE_CRON_SCHEDULE }}"
          nxd_discord_prefix       = "${{ secrets.NXD_DISCORD_PREFIX }}"
          nxd_discord_token        = "${{ secrets.NXD_DISCORD_TOKEN }}"
          nxd_db_uri               = "${{ secrets.NXD_DB_URI }}"
          nxd_db_name              = "${{ secrets.NXD_DB_NAME }}"
          nxd_db_user              = "${{ secrets.NXD_DB_USER }}"
          nxd_db_password          = "${{ secrets.NXD_DB_PASSWORD }}"
          nxd_cron_interval        = "${{ secrets.NXD_CRON_INTERVAL }}"
          nxd_log_json             = "${{ secrets.NXD_LOG_JSON }}"
          nxd_log_level            = "${{ secrets.NXD_LOG_LEVEL }}"
          nxd_newrelic_name        = "${{ secrets.NXD_NEWRELIC_NAME }}"
          nxd_newrelic_license_key = "${{ secrets.NXD_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Import Terraform
        run: |
          terraform import -input=false google_container_cluster.cluster ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}
          terraform import -input=false google_container_node_pool.pool ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}/${{ secrets.GKE_POOL_NAME }}
          terraform import -input=false kubernetes_deployment.bot default/${{ secrets.GKE_DEPLOYMENT_NAME }}
          terraform import -input=false kubernetes_cron_job_v1.cron default/${{ secrets.GKE_CRON_NAME }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}